# Generated by Django 4.2.27 on 2026-01-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('personal', 'Personal'), ('enterprise', 'Enterprise')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Annual'), ('lifetime', 'Lifetime')], default='month', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('cv_templates', models.PositiveIntegerField(default=1)),
                ('max_cv_sections', models.PositiveIntegerField(default=12)),
                ('access_design_tools', models.BooleanField(default=False)),
                ('access_quizzes', models.BooleanField(default=False)),
                ('access_roadmap', models.BooleanField(default=False)),
                ('unlock_skill_challenges', models.BooleanField(default=False)),
                ('realtime_cv_suggestions', models.BooleanField(default=False)),
                ('progress_tracking', models.BooleanField(default=False)),
                ('public_career_roadmaps', models.BooleanField(default=False)),
                ('pdf_export', models.BooleanField(default=False)),
                ('stripe_price_id', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
