# Generated by Django 4.2.27 on 2026-01-11 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('BASIC', 'Basic'), ('PRO', 'Pro'), ('STANDARD', 'Standard')], max_length=20)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], max_length=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('percent_off', models.PositiveIntegerField(default=0)),
                ('amount_off', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='access_design_tools',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='access_quizzes',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='access_roadmap',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='cv_templates',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_cv_sections',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='pdf_export',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price_cents',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='progress_tracking',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='public_career_roadmaps',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='realtime_cv_suggestions',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='unlock_skill_challenges',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.plan')),
                ('price_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.planprice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='planprice',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='billing.plan'),
        ),
        migrations.CreateModel(
            name='BillingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=80)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.plan')),
                ('price_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.planprice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_orders', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.voucher')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='planprice',
            unique_together={('plan', 'tier', 'billing_cycle')},
        ),
    ]
