# Generated by Django 6.0 on 2026-02-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvtemplate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cvtemplate',
            name='template_file',
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='html_content',
            field=models.TextField(default='Noi Dung HTML'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvtemplate',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='cv_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='cvtemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
