# Generated by Django 6.0 on 2026-02-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_cvtemplate_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvtemplate',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='cv_templates_source/'),
        ),
    ]
