# Generated by Django 6.0 on 2026-02-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cvtemplate_description_alter_cvtemplate_html_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
