# Generated by Django 6.0 on 2026-02-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_file', models.FileField(blank=True, null=True, upload_to='cv_templates_source/')),
            ],
        ),
    ]
