# Generated by Django 6.0 on 2026-01-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Chức danh công việc')),
                ('company_name', models.CharField(max_length=255, verbose_name='Tên công ty')),
                ('location', models.CharField(max_length=255, verbose_name='Địa điểm làm việc')),
                ('salary_range', models.CharField(max_length=100, verbose_name='Mức lương')),
                ('description', models.TextField(verbose_name='Mô tả công việc')),
                ('requirements', models.TextField(verbose_name='Yêu cầu ứng viên')),
                ('benefits', models.TextField(blank=True, null=True, verbose_name='Quyền lợi')),
                ('deadline', models.DateField(verbose_name='Hạn nộp hồ sơ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
