# Generated by Django 6.0 on 2026-01-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(default='IT Software', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(default='Không yêu cầu', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Toàn thời gian'), ('Part-time', 'Bán thời gian'), ('Freelance', 'Freelance'), ('Internship', 'Thực tập')], default='Full-time', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='logo',
            field=models.CharField(blank=True, default='https://via.placeholder.com/150', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.CharField(default='Ngăn cách bằng dấu phẩy', help_text='Ngăn cách bằng dấu phẩy', max_length=255),
            preserve_default=False,
        ),
    ]
