# Generated by Django 6.0 on 2026-01-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(verbose_name='Nội dung trích xuất từ PDF')),
                ('analysis_result', models.JSONField(verbose_name='Kết quả JSON từ AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
